-- DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
`id` INT NOT NULL AUTO_INCREMENT,
`ime` VARCHAR(150) NOT NULL,
`prezime` VARCHAR(150) NOT NULL,
`broj_telefona` VARCHAR(150) NOT NULL,
`email` VARCHAR(150) NOT NULL,
`password` VARCHAR(256) NOT NULL,
PRIMARY KEY (`id`)
)
COLLATE='utf16_bin'
ENGINE=InnoDB;